
let songs = [
    {"album": 1, "title": "BOMB (Feat. San E)"},
    {"album": 1, "title": "Rose (Feat. 켄 of VIXX)"},
    {"album": 1, "title": "Ladi Dadi (Feat. Microdot, JERO)"},
    {"album": 1, "title": "나홀로 집에 (Feat. 정용화)"},
    {"album": 1, "title": "아 몰라 일단 Do The Dance"}, // ㅇ 4
    {"album": 1, "title": "Lean on me"}, // L 5
    {"album": 1, "title": "뇌비우스의 띠 (Feat. ESBEE)"},  // ㄴ 6

    {"album": 2, "title": "MOVE"},
    {"album": 2, "title": "Lean on me"}, // L 8 
    {"album": 2, "title": "OX (Feat. Basick)"},
    {"album": 2, "title": "뇌비우스의 띠 (Feat. ESBEE)"}, // ㄴ 10
    {"album": 2, "title": "Control (Interlude)"},
    {"album": 2, "title": "끄덕끄덕 (Feat. Donutman)"},
    {"album": 2, "title": "착한 여자 (Feat. 한해, Soulman)"},
    {"album": 2, "title": "아 몰라 일단 Do The Dance"},  // ㅇ 14
    {"album": 2, "title": "Where should I go (Feat. MICRODOT)"},
    {"album": 2, "title": "Where should I go (Solo ver.)"},
    {"album": 2, "title": "Who Are U (Feat. Superbee)"},
    {"album": 2, "title": "자각몽 (Feat. MICRODOT)"},
    {"album": 2, "title": "홍길동"},
 
    {"album": 3, "title": "끓는점 (Feat. Sik-K)"},
    {"album": 3, "title": "CHAMELEON"},
    {"album": 3, "title": "NIRVANA (Feat. 박지민)"},
    {"album": 3, "title": "RAVI DA LOCA	"},
    {"album": 3, "title": "PAYDAY (Feat. 최초아, OLNL)"},
    {"album": 3, "title": "ALCOHOL"},
    {"album": 3, "title": "WHERE AM I (Feat. MICRODOT)"},

    {"album": 4, "title": "PAYBACK (Feat. Coogie)"},
    {"album": 4, "title": "SPARRING"},
    {"album": 4, "title": "FRYPAN (Feat. Double K, Microdot)"},
    {"album": 4, "title": "파블로프의 개 (Feat. Cold Bay, Basick)"},
    {"album": 4, "title": "SCARYNIGHTT"},
    {"album": 4, "title": "(Bonus Track) SHOT"},

    {"album": 5, "title": "R.OOK BOOK"},
    {"album": 5, "title": "TUXEDO"},
    {"album": 5, "title": "L.A.Y.E.R.E.D (Feat. SAAY)"},
    {"album": 5, "title": "녹는점 (See-Through) (Feat. Cold Bay)"},
    {"album": 5, "title": "RUNWAY"},
    {"album": 5, "title": "U-NIVERSE (Cosmocorps) (Feat. Rick bridges)"},
    {"album": 5, "title": "HOODIE (Feat. Xydo, Raf Sandou)"},
    {"album": 5, "title": "(Bonus track) live (Feat. 청하)"},

    {"album": 6, "title": "TWO TONE DRIP (Feat. 박지우, Make A Movie) (Prod. Cosmic Boy)"},
    {"album": 6, "title": "LEOPARD (Feat. 솔라 of 마마무) (Prod. Cosmic Boy)"},
    {"album": 6, "title": "STILL NIRVANA (Feat. 김하온 (HAON), Xydo (시도)) (Prod. PUFF)"},
    {"album": 6, "title": "O.I (Prod. GXXD)"},
    {"album": 6, "title": "VERSA (Prod. YUTH)"},
    {"album": 6, "title": "고객 (SERVICE) (Prod. YUTH)"},
    {"album": 6, "title": "UNICORN (Feat. Cold Bay (콜드베이)) (Prod. GXXD)"},

    {"album": 7, "title": "NZT (Prod. YUTH)"},
    {"album": 7, "title": "LIMITLESS (Feat. Sik-K, Xydo (시도)) (Prod. YUTH)"},
    {"album": 7, "title": "VENOM (Feat. Ja Mezz) (Prod. DAKSHOOD)"},
    {"album": 7, "title": "ZOMBIE (Prod. Flash Note)"},
    {"album": 7, "title": "BADA$$ (Feat. Cold Bay (콜드베이)) (Prod. Flash Note)"},
    {"album": 7, "title": "BRAG (Feat. Chillin Homie) (Prod. Flash Note)"},
    
    {"album": 8, "title": "Q&A (Feat. ZENE THE ZILLA) (Prod. YUTH)"},
    {"album": 8, "title": "HOW COULD YOU (Feat. Raf Sandou) (Prod. YUTH)"},
    {"album": 8, "title": "TURN ON THE LIGHT (Feat. twlv) (Prod. YUTH)"},
    {"album": 8, "title": "DRUG (Feat. 김효은) (Prod. Cool Cat)"},
    {"album": 8, "title": "각성 (AROUSAL) (Prod. YUTH)"},

    {"album": 9, "title": "EL DORADO (Prod. PUFF)"},
    {"album": 9, "title": "PO$EI (Feat. Khundi Panda) (Prod. PUFF)"},
    {"album": 9, "title": "DREAM CATCHER (Feat. Reddy, BILL STAX (빌스택스)) (Prod. Flash Note)"},
    {"album": 9, "title": "LO-FI (Feat. 식케이 (Sik-K)) (Prod. Flash Note, PUFF)"},
    {"album": 9, "title": "ROCKSTAR (Feat. Paloalto) (Prod. YUTH)"},
    {"album": 9, "title": "GODDESS (Feat. Xydo (시도)) (Prod. CLAM)"},
    {"album": 9, "title": "여포 (呂布) (Feat. Rohann (이로한), Chillin Homie) (Prod. QUIZQUIZ)"},
    {"album": 9, "title": "DOBERMAN (Feat. 지투 (G2)) (Prod. Flash Note)"},
    {"album": 9, "title": "FULL TIME DIGGA (Feat. sokodomo, Raf Sandou) (Prod. Flash Note)"},
    {"album": 9, "title": "칼춤 (劍舞) (Feat. Xydo (시도), Cold Bay (콜드베이), Chillin Homie) (Prod. CLAM)"},
    {"album": 9, "title": "(BONUS TRACK) WHERE AM I (GROOVL1N REMIX)"},

    {"album": 10, "title": "유턴(U-TURN)"},
    {"album": 10, "title": "PARADISE(Feat. 하성운)"},
    {"album": 10, "title": "WATER GUN"},
    {"album": 10, "title": "QUESTION MARK"},
    {"album": 10, "title": "IF I(Feat. BIG Naughty(서동현))(Prod. WOOGIE)"},
    {"album": 10, "title": "비♡(Feat. 이나은 of 에이프릴(APRIL))"},

    {"album": 11, "title": "꽃밭(FLOWER GARDEN)"},
    {"album": 11, "title": "CARDIGAN(feat. 원슈타인)"},
    {"album": 11, "title": "CHEE$E(feat. BLNK, 안병웅)"},
    {"album": 11, "title": "ROSES"},
    {"album": 11, "title": "어는점(feat. Xydo)"},
    {"album": 11, "title": "I DON’T DENY"},
    
    {"album": 12, "title": "GUNS"},
    {"album": 12, "title": "VIRUS(feat.JUSTHIS)"},
    {"album": 12, "title": "WINNER(feat.ASH ISLAND)"},
    {"album": 12, "title": "LOVE HATE FIGHT(feat.nafla)"},
    {"album": 12, "title": "WHAT’S MY PROBLEM"},
    {"album": 12, "title": "LET ME DOWN SLOWLY(feat.Cold Bay)"},
    {"album": 12, "title": "DROWNING IN THE RAIN"},
    {"album": 12, "title": "1,2,3(feat.Xydo)"},
    {"album": 12, "title": "CANNONBALL(feat.Paul Blanco)"},
    {"album": 12, "title": "애니(feat.소연 ((여자)아이들))"},
    {"album": 12, "title": "WARRIOR"},

    {"album": 13, "title": "말투(feat. Leellamarz)(prod. TOIL)"},
    {"album": 13, "title": "꿈속에"},
    {"album": 13, "title": "빈자리(feat. 수엔(Suen))"},
    {"album": 13, "title": "데리러 갈게"},
    {"album": 13, "title": "잔잔하게"},
    
    {"album": 14, "title": "내버려둬 (feat. Jayci yucca)"},
    {"album": 14, "title": "KISS YOU"},
    {"album": 14, "title": "DUMB DUMB DUMB"},
    {"album": 14, "title": "지독하게 엮여"},
    {"album": 14, "title": "방해금지(feat. 아우릴고트, 365lit, Blase)"},
    {"album": 14, "title": "MIRROR (feat. Polodared)"},
    {"album": 14, "title": "JOE GOLDBERG"},
    {"album": 14, "title": "CAMERA"},
    {"album": 14, "title": "BYE (feat. 휘인)"},
    {"album": 14, "title": "HOLIDAY"},
]